# Generated by Django 5.0.7 on 2024-09-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='payment_date',
            new_name='receipt_date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
