# Generated by Django 5.0.7 on 2024-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_payment_date_receipt_receipt_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cart_items',
            field=models.JSONField(default=list),
        ),
    ]
